spring:
  datasource:
    url: jdbc:oracle:thin:@127.0.0.1:1521:orcl
    username: sde
    password: 123456

mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:com.gisquest.ga.mapper/*.xml

ga:
  ellipse: 2000
  centralmeridian: 120
  dai: 40
  srid: 4528