spring:
  datasource:
    url: jdbc:oracle:thin:@127.0.0.1:1521:orcl
    username: sde
    password: 123456
  redis:
    #数据库索引
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
    jedis:
      pool:
        #最大连接数
        max-active: 8
        #最大阻塞等待时间(负数表示没限制)
        max-wait: -1
        #最大空闲
        max-idle: 8
        #最小空闲
        min-idle: 0
    #连接超时时间
    timeout: 10000


mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:com.gisquest.ga.mapper/*.xml


ga:
  ellipse: 2000
  centralmeridian: 120
  dai: 40
  srid: 4528